// Code generated by counterfeiter. DO NOT EDIT.
package cgroupsfakes

import (
	"sync"

	"code.cloudfoundry.org/guardian/rundmc/cgroups"
)

type FakeMountFunc struct {
	Stub        func(source, target string, fstype string, flags uintptr, data string) error
	mutex       sync.RWMutex
	argsForCall []struct {
		source string
		target string
		fstype string
		flags  uintptr
		data   string
	}
	returns struct {
		result1 error
	}
	returnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeMountFunc) Spy(source string, target string, fstype string, flags uintptr, data string) error {
	fake.mutex.Lock()
	ret, specificReturn := fake.returnsOnCall[len(fake.argsForCall)]
	fake.argsForCall = append(fake.argsForCall, struct {
		source string
		target string
		fstype string
		flags  uintptr
		data   string
	}{source, target, fstype, flags, data})
	fake.recordInvocation("MountFunc", []interface{}{source, target, fstype, flags, data})
	fake.mutex.Unlock()
	if fake.Stub != nil {
		return fake.Stub(source, target, fstype, flags, data)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.returns.result1
}

func (fake *FakeMountFunc) CallCount() int {
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	return len(fake.argsForCall)
}

func (fake *FakeMountFunc) ArgsForCall(i int) (string, string, string, uintptr, string) {
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	return fake.argsForCall[i].source, fake.argsForCall[i].target, fake.argsForCall[i].fstype, fake.argsForCall[i].flags, fake.argsForCall[i].data
}

func (fake *FakeMountFunc) Returns(result1 error) {
	fake.Stub = nil
	fake.returns = struct {
		result1 error
	}{result1}
}

func (fake *FakeMountFunc) ReturnsOnCall(i int, result1 error) {
	fake.Stub = nil
	if fake.returnsOnCall == nil {
		fake.returnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.returnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeMountFunc) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.mutex.RLock()
	defer fake.mutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeMountFunc) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ cgroups.MountFunc = new(FakeMountFunc).Spy
